version: '3.6'

services:
    postgres:
        image: postgres:16.1-alpine
        ports:
            - '5432:5432'
        env_file:
            - .env.db

    smtp:
        image: axllent/mailpit:v1.12.1
        environment:
            TZ: Europe/London
        ports:
            - '1025:1025'
            - '8025:8025'
